### PR TITLE
Adding Dockerfile support

### LINKED ISSUE #75: Add Docker Hub automated build for supervisord
May I suggest the addition of a `Dockerfile` and configuration of an automated build on [Docker Hub](https://hub.docker.com/). That way those wishing to add `supervisord` to a Docker image could simply do:

```Dockerfile
COPY --from=ochinchina/supervisord:latest /usr/local/bin/supervisord /usr/local/bin/supervisord
```

Perhaps something along the lines of:

```Dockerfile
FROM golang:latest

ADD . /go/src/github.com/ochinchina/supervisord
RUN go build -o /usr/local/bin/supervisord github.com/ochinchina/supervisord

ENTRYPOINT ["supervisord"]
```

Once Docker Hub supports [multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/) more space efficient and Alpine based build could be added.

### PR DESCRIPTION
**Pull request by Rbeuque74**
Fix #75

Signed-off-by: Romain Beuque <romain.beuque@gmail.com>

### CODE REVIEW

**Comment by rwlincoln** [comment]
I was under the impression that `alpine` images use `musl` rather than `glibc`. For this image to work, wouldn't `CGO_ENABLED=0` and perhaps `-installsuffix cgo` have to be set. This might not be desirable given the dependency on `golang.org/x/sys`. Separate `debian` and `alpine` based images would be ideal.

**Comment by Rbeuque74** [comment]
IMO, image was not meant to be used by itself, but to be exported into another image, so I choose to package it into a alpine image to reduce the size of docker pull.

No one should just ```docker run -it --rm ochinchina/supervisord```, as it's necessary to add supervisor config file inside.

Separated tag for 2 differents images means 2 Dockerfile, am I right ?

**Comment by rwlincoln** [comment]
If the image is intended to only be used in the way you suggest then we could do `FROM scratch`. However, we should account for users possibly working with the image in the conventional way. Either passing in a config using a volume or doing `FROM ochinchina/supervisord`.

> Separated tag for 2 differents images means 2 Dockerfile, am I right ?

This is what I was referring to by multi-stage support on Docker Hub. Right now I can't see how a target argument can be specified though the UI:

https://docs.docker.com/develop/develop-images/multistage-build/#stop-at-a-specific-build-stage

With that we could do it all in one Dockerfile. An alternative would be to add building an uploading the images as a stage in the CI config. For now I suggest we change the Dockerfile to something like:

```Dockerfile
FROM golang:latest as builder

ADD . /go/src/github.com/ochinchina/supervisord
RUN go install github.com/ochinchina/supervisord

FROM debian:stretch
COPY --from=builder /go/bin/supervisord /usr/local/bin/supervisord
ENTRYPOINT ["supervisord"]
```

`supervisord` uses dep all of the dependencies should already be in `/vendor` and the `go get` command should not be required.

Alternatively, we could do it with `alpine` images, but both `alpine` and `debian` with separate tags would be best:

```Dockerfile
FROM golang:alpine as builder

ADD . /go/src/github.com/ochinchina/supervisord
RUN go install github.com/ochinchina/supervisord

FROM alpine
COPY --from=builder /go/bin/supervisord /usr/local/bin/supervisord
ENTRYPOINT ["supervisord"]
```

**Comment by rwlincoln** [comment]
As an alternative to building and pushing the images using the CI config, it seems we could extend the existing `goreleaser` configuration:

https://goreleaser.com/#docker

As it stands, it would make more sense include a binary in the GitHub release and recommend adding it to containers using `ADD`:

https://docs.docker.com/engine/reference/builder/#add

For example:

```Dockerfile
ADD https://github.com/ochinchina/supervisord/releases/download/v0.3/supervisord-linux-amd64 /usr/local/bin/supervisord
```

**Comment by Rbeuque74** [comment]
Right now, there is no vendor folder in the project.

Using goreleaser and artifact from the releases seems to be a really interesting way to include it into a Docker images, I like it too :)

**Pull request merged**
