### PR TITLE
fix syslog and syscall to support windows

### PR DESCRIPTION
**Pull request by chendh521**
`syslog.Writer`, `syscall.SysProcAttr{Setpgid: true}` and `syscall.Kill` are not supported in Windows.
see: https://golang.org/pkg/log/syslog/#pkg-note-BUG

So I just created 3 new files from the linux ones: `log_windows.go`, `process_windows.go` and `supervisor_windows.go`. 
Most of these 3 windows ones are same as the linux ones. I think you can reedit and reorg the files and code structure.

### CODE REVIEW

**Comment by ochinchina** [comment]
There is only one minor difference between the windows and the Linux on the SysLogger. In the Windows, the syslog is not supported, so only the function NewSysLogger should be different between the Linux and windows.

we can define logger_windows.go and logger_unix.go. In the logger_windows.go and logger_unix.go only the method NewSysLogger  is defined. The logger_windows.go simply set the logWriter  to nil. The current NewSysLogger  is simply moved to the  logger_unix.go file.

**Comment by chendh521** [comment]
@ochinchina Follow ur suggestion, I removed the repeated code. There're mainly 2 changes:
   1. add logger_windows.go and logger_linux.go, to solve the `syslog.Writer` incompatibility in windows.
   2. add process_windows.go and process_linux.go, to solve the `syscall.SysProcAttr{Setpgid: true}` and `syscall.Kill` incompatibility in windows.

Pls review.

**Comment by ochinchina** [comment]
1) the windows related signal is in the signal_windows.go already, only needs to change method toSignal.
2) for the Setpgid, it is already in pdeathsig_xxx.go, simply remove the parameter Setpgid in syscall.SysProcAttr constructor.
3) the syslog related code only need to implement NewSyslogger() method for different platform, so let the Syslogger class definition and all other methods in the log.go file.

**Comment by chendh521** [comment]
Just saw you've already fixed. Then I can close this pull request.

**Pull request closed without merging**
